# mysql
spring:
  #  thymeleaf:
  #    prefix: classpath:/templates/
  #    cache: false
  datasource:
    #MySQL配置
    url: jdbc:mysql://localhost:3306/vuedemo2?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 135583
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model
server:
  port: 9000
